table table_third_parties
	lineageTag: b72fb869-99b2-40bb-92fb-c12f4fab6bad

	column IdTipoIdentificacion
		dataType: int64
		formatString: 0
		lineageTag: 5c925eb1-0934-4a82-a560-8d748e581aca
		summarizeBy: sum
		sourceColumn: IdTipoIdentificacion

		annotation SummarizationSetBy = Automatic

	column Identificacion
		dataType: string
		lineageTag: ad3f895c-536e-4058-80a8-3d4975cba7b8
		summarizeBy: none
		sourceColumn: Identificacion

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 7e0c3873-c72e-479d-b3fc-d792915ca9d7
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column IdentificacionCiudad
		dataType: int64
		formatString: 0
		lineageTag: be05932c-ca45-438b-8f50-5390ec7d8990
		summarizeBy: sum
		sourceColumn: IdentificacionCiudad

		annotation SummarizationSetBy = Automatic

	column Propiedades
		dataType: string
		lineageTag: 13b3bed9-409d-44ca-a5be-e35f13734f3d
		summarizeBy: none
		sourceColumn: Propiedades

		annotation SummarizationSetBy = Automatic

	column Nombre_Terceros
		dataType: string
		lineageTag: 8ea6d7ab-f2b4-4a0e-b598-41539c1304d6
		summarizeBy: none
		sourceColumn: Nombre_Terceros

		annotation SummarizationSetBy = Automatic

	partition table_third_parties = m
		mode: import
		source =
				let
				    Origen = Sql.Database("SRFWDCONT01\WORLDOFFICE19", "WEARE DEV SAS"),
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([Name] <> "aActualizacionesBasesDatosSQL" and [Name] <> "aActualizacionesScripts" and [Name] <> "aActualizacionesSQL" and [Name] <> "aConstantesSQL" and [Name] <> "Actividades_Clases" and [Name] <> "Actividad_Configuracion" and [Name] <> "ActivosFijos" and [Name] <> "ActivosFijosInfAXI" and [Name] <> "ActivosFijosInfAXI_Anual" and [Name] <> "ActivosFijosporFechaGarantia" and [Name] <> "ActivosFijosporFechaSeguro" and [Name] <> "ActivosFijosxCentrodeCostos" and [Name] <> "ActivosFijosxUbicacionYResponsable" and [Name] <> "ActivosFijos_Cod_CUBSO_Peru" and [Name] <> "ActivosFijos_Depreciacion_Metodos" and [Name] <> "ActivosFijos_Estados_Peru" and [Name] <> "ActivosFijos_FactorDep" and [Name] <> "Activos_Fijos_Acumulados" and [Name] <> "Activos_Fijos_DepHistorica" and [Name] <> "Activos_Fijos_Mantenimiento" and [Name] <> "Activo_Fijo_Doc_Inicial" and [Name] <> "ActualizacionEjecucion" and [Name] <> "ActualizacionEnProceso" and [Name] <> "aEventosSQL" and [Name] <> "AIU" and [Name] <> "Alquiler_Aplicacion" and [Name] <> "Alquiler_detalle" and [Name] <> "Alquiler_Devueltos" and [Name] <> "Alquiler_Movimiento" and [Name] <> "Alquiler_Saldo1" and [Name] <> "Alquiler_Saldo2" and [Name] <> "Alquiler_Saldo3" and [Name] <> "Alquiler_total" and [Name] <> "Anios" and [Name] <> "AplicaNormaUvtIndep" and [Name] <> "AplicaRteFTeProc2" and [Name] <> "AportesDias" and [Name] <> "AportesRedondeoSMLV" and [Name] <> "Aportes_Centros_Trabajo" and [Name] <> "Aportes_Configuracion_Planilla" and [Name] <> "Aportes_Datos_Contrato" and [Name] <> "Aportes_DiasTurnos_Tipo_51" and [Name] <> "Aportes_FactorParafiscal" and [Name] <> "Aportes_HistoricoPlanilla" and [Name] <> "Aportes_Horas" and [Name] <> "Aportes_IBC" and [Name] <> "Aportes_IBC_AUX" and [Name] <> "Aportes_IBC_Nomina_1" and [Name] <> "Aportes_IBC_Nomina_2" and [Name] <> "Aportes_IBC_Nomina_3" and [Name] <> "Aportes_IBC_PERU" and [Name] <> "Aportes_IBC_Vac_1" and [Name] <> "Aportes_IBC_Vac_2" and [Name] <> "Aportes_IBC_Vac_3" and [Name] <> "Aportes_Novedades" and [Name] <> "Aportes_Novedades_Detalle" and [Name] <> "Aportes_Novedades_Encab" and [Name] <> "Aportes_Planilla_CambioContratoSena" and [Name] <> "Aportes_Planilla_Paso1" and [Name] <> "Aportes_Planilla_Paso2" and [Name] <> "Aportes_Planilla_Paso3" and [Name] <> "Aportes_Planilla_Paso3_1" and [Name] <> "Aportes_SubTipoCotizacion" and [Name] <> "Aportes_TablaRangoTipo51" and [Name] <> "Aportes_TarifaEspecialPension" and [Name] <> "Aportes_Tercero" and [Name] <> "Aportes_TerceroFondo_ARP" and [Name] <> "Aportes_TerceroFondo_Caja" and [Name] <> "Aportes_TerceroFondo_Eps" and [Name] <> "Aportes_TerceroFondo_Pension" and [Name] <> "Aportes_TieneAporteConfigurado" and [Name] <> "Aportes_TipoCotizacion" and [Name] <> "Aportes_TipoFondo_Novedades" and [Name] <> "Aportes_TipoIncapacidad" and [Name] <> "Aportes_TopesFonsol" and [Name] <> "Aportes_Total_Empleados" and [Name] <> "Aportes_Valor_1" and [Name] <> "Aportes_Valor_2" and [Name] <> "ARL_ClaseRiesgo" and [Name] <> "ArrayListWo" and [Name] <> "AsientoFuenteEsDS" and [Name] <> "AsientoFuenteEsFe" and [Name] <> "Asist_Configuracion_Filtros" and [Name] <> "Asist_Descripcion_Campos" and [Name] <> "Asist_Informe" and [Name] <> "Asist_Informe_Campos" and [Name] <> "Asist_Origenes_Filtros" and [Name] <> "Asist_Tipo_Informe" and [Name] <> "Asist_Tipo_Informe_Filtros" and [Name] <> "AudDifDocP1" and [Name] <> "AudDifDocP2" and [Name] <> "AuditoriaConfig" and [Name] <> "AuditoriaConfigCampos" and [Name] <> "AuditoriaConfigTablas" and [Name] <> "AuditoriaDatos" and [Name] <> "AuditoriaDatosDet" and [Name] <> "AuditoriaLog" and [Name] <> "AuditoriaProcesar" and [Name] <> "AuditoriaTablas" and [Name] <> "Auditoria_Docs_DifTotalContable" and [Name] <> "Auditoria_Docs_DifTotalContable_Paso1" and [Name] <> "Auditoria_Docs_DifTotalInventario" and [Name] <> "Auditoria_Docs_DifTotalInventario_Paso1" and [Name] <> "Auditoria_GetWhereSentence" and [Name] <> "Audit_conta_Costo_Ventas" and [Name] <> "Audit_TercerosMalAbonados_Paso1" and [Name] <> "Autorretenciones_Renta_AuxiliarImpuestos" and [Name] <> "Ayuda_Controles" and [Name] <> "Busqueda_ModelosContabilizacion" and [Name] <> "CajasResolucion" and [Name] <> "CalculaMontoMonetarioSQL" and [Name] <> "CalculoComisionRecaudo" and [Name] <> "CalculoComisionVentas" and [Name] <> "CalculoImpuestoPeruRteQuinta" and [Name] <> "CalculoRetencionPorMinima" and [Name] <> "CalculoRetencionPorMinimaPorc" and [Name] <> "CalculoRetencionPorUVT" and [Name] <> "CalculoRetencionPorUVTPorc" and [Name] <> "CalculoRetencionPorUVT_textopie" and [Name] <> "Campos_Pers_Docum" and [Name] <> "Campos_Pers_Docum_Formulas" and [Name] <> "Campos_Pers_Docum_Indices" and [Name] <> "Cancelacion_Cuentas_Peru" and [Name] <> "CantidadExistenciasMaterialRequerido" and [Name] <> "CantidadVecesDiaPeriodo" and [Name] <> "Cantidad_EPT" and [Name] <> "Cantidad_Importacion" and [Name] <> "CarPlanPagos" and [Name] <> "Cartera_ProximoPago_Paso0" and [Name] <> "Cartera_ProximoPago_Paso0_0" and [Name] <> "Cartera_ProximoPago_Paso1" and [Name] <> "CCAD_Auxiliar" and [Name] <> "CCA_Clasificaciones" and [Name] <> "CCA_Codeudores" and [Name] <> "CCA_Cuotas" and [Name] <> "CCA_M_Inventarios" and [Name] <> "CCA_M_Inventarios_Caracteristicas" and [Name] <> "CCA_M_Inventarios_MasInfo_Movimientos" and [Name] <> "CCA_M_Inventarios_SenEnvio" and [Name] <> "CCA_M_Inventarios_Tipo_IGV_Peru" and [Name] <> "CCA_M_Inventarios_Tipo_Obsequio" and [Name] <> "CCA_Valores_Peru" and [Name] <> "CCC_Detalles" and [Name] <> "CCC_Inventario" and [Name] <> "CCC_P" and [Name] <> "CCC_Retenciones" and [Name] <> "CCC_R_Tarifas" and [Name] <> "CCD_Clasificaciones" and [Name] <> "CCD_Clasificaciones_Inventario" and [Name] <> "CesantiasGenyCan" and [Name] <> "Ciudades" and [Name] <> "CiudadesDIAN_Colombia" and [Name] <> "Clasificacion_Dian" and [Name] <> "ClasifPizza" and [Name] <> "Clientes_Sin_Facturacion_Plus" and [Name] <> "Comis-Eventos" and [Name] <> "Comis-Inventario" and [Name] <> "Comis-Porcentaje" and [Name] <> "Comis-Tipos" and [Name] <> "ComisionesPorRecaudo" and [Name] <> "Comision_FormaPagoGruposTotalFV_DMC" and [Name] <> "Comision_FormaPagoGruposTotalFV_Paso2" and [Name] <> "Comision_FormasPago" and [Name] <> "Comision_Recaudo_Intervalos" and [Name] <> "Comision_Recaudo_Terceros" and [Name] <> "Comision_Recaudo_Tipos" and [Name] <> "Comision_Ventas_Interv" and [Name] <> "Comision_Ventas_Intervalos" and [Name] <> "Comision_Ventas_Terceros" and [Name] <> "Compras_por_Cliente" and [Name] <> "Compras_por_Cliente_FiltroDoc" and [Name] <> "Compras_por_Comprador_y_Proveedor_ComparativoFNC" and [Name] <> "Compras_por_Proveedor" and [Name] <> "Compra_Remisionada_Cruces" and [Name] <> "Comprobante_Egreso_Estado_Cuenta" and [Name] <> "Comprobante_Egreso_Estado_Cuenta_Caja_Menor" and [Name] <> "Comprobante_Egreso_Estado_Cuenta_MonedaExt" and [Name] <> "Comprobante_Egreso_Estado_Cuenta_MonedaExt_Caja_Menor" and [Name] <> "ConceptoFactorVac" and [Name] <> "ConceptosAdicionalesPorTercero" and [Name] <> "ConceptosDotacion" and [Name] <> "Conceptos_Nomina_DIAN" and [Name] <> "Conciliacion Bancaria - Conceptos" and [Name] <> "Conciliacion Bancaria - Detalles" and [Name] <> "ConciliacionBancariaAuto_Contab_SQL" and [Name] <> "ConciliacionBancariaAuto_Extracto_SQL" and [Name] <> "ConciliacionBancaria_Automatica" and [Name] <> "ConciliacionBancaria_Extracto" and [Name] <> "ConciliacionBancaria_Extracto_Detalle" and [Name] <> "ConciliacionBancaria_Plantilla" and [Name] <> "ConciliacionBancaria_Plantilla_Ajuste" and [Name] <> "ConciliacionBancaria_Plantilla_Exclusiones" and [Name] <> "ConciliacionBancaria_Temp_Ajustes_Prop" and [Name] <> "ConfiguracionCorreo" and [Name] <> "ConfiguracionInicial_Nomina_Tipos" and [Name] <> "Configuracion_Basculas" and [Name] <> "Configuracion_Basculas_Plantilla" and [Name] <> "Configuracion_Inicial_Nomina_Temp" and [Name] <> "Config_Correo_SMTP" and [Name] <> "Config_Informes" and [Name] <> "Config_Informes_Detalles_Cuentas_Contables" and [Name] <> "Config_Teclas_Pos" and [Name] <> "Conf_Aportes_Liquidacion" and [Name] <> "Conf_Prestaciones_Anticipos_Emp" and [Name] <> "Conf_Prestaciones_Anticipos_Tipos" and [Name] <> "Conf_Prestaciones_Causal_Despido" and [Name] <> "Conf_Prestaciones_ConfigAportes" and [Name] <> "Conf_Prestaciones_Cta_Factor" and [Name] <> "Conf_Prestaciones_Festivos" and [Name] <> "Conf_Prestaciones_Liquidacion" and [Name] <> "Conf_Prestaciones_LiquidacionEncab" and [Name] <> "Conf_Prestaciones_LiquidacionNovedad" and [Name] <> "Conf_Prestaciones_Liquidacion_Asientos" and [Name] <> "Conf_Prestaciones_Tipos" and [Name] <> "Conf_Retencion_Indep" and [Name] <> "Consignacion_Bancaria_EstadoCuenta_Extranjero" and [Name] <> "Consignacion_Bancaria_EstadoCuenta_Paso1" and [Name] <> "Consignacion_Bancaria_EstadoCuenta_Paso2" and [Name] <> "Constantes" and [Name] <> "Constantes_Ayudas" and [Name] <> "Contratacion_ContratoTerceros" and [Name] <> "Contratacion_Procesos" and [Name] <> "Contratacion_TipoProceso" and [Name] <> "controlesheredados" and [Name] <> "Conversion_PUC_Pais" and [Name] <> "convierteFormatoNumero" and [Name] <> "Correo_Interno_Mensajes" and [Name] <> "Costarica_Pres_Aguinaldo_Acumulados" and [Name] <> "CostaRica_Pres_Aguinaldo_Devengado_Paso1" and [Name] <> "CostaRica_Pres_Aguinaldo_PorConceptos_Previa" and [Name] <> "CostaRica_Pres_Aguinaldo_VistaPrevia" and [Name] <> "CostaRica_Pres_Anticipos" and [Name] <> "CostaRica_Pres_Ausencias" and [Name] <> "CostoOrdenProduccion_OPTIM" and [Name] <> "CostoPromedio" and [Name] <> "CostoPromedio1" and [Name] <> "CostoVentasVendedor" and [Name] <> "Costo_Promedio_Busqueda" and [Name] <> "Costo_Promedio_Busqueda_Paso1" and [Name] <> "Costo_Promedio_Busqueda_Paso2" and [Name] <> "Costo_Promedio_Empresa" and [Name] <> "Costo_Promedio_Fecha" and [Name] <> "Costo_Promedio_OP" and [Name] <> "Costo_Promedio_OP_Nuevo" and [Name] <> "Costo_Promedio_Recetas_paso1" and [Name] <> "Costo_Promedio_Recetas_Paso2" and [Name] <> "Cotizacion_Proveedores_Cruces" and [Name] <> "CruceImportaciones" and [Name] <> "CtaAsientosMetodoPagos" and [Name] <> "CuentaConFormatoPaises" and [Name] <> "Cuentas Contables -Contabilizaciones-Encabezado" and [Name] <> "Cuentas Contables -Contabilizaciones-Manejo" and [Name] <> "CuentasContables" and [Name] <> "CuentasContables - Asientos" and [Name] <> "CuentasContables - Asientos - Detalles" and [Name] <> "CuentasContables - Asientos - Notas" and [Name] <> "CuentasContables - Asientos-MasInfoSubTipos" and [Name] <> "CuentasContables - Asientos-MasInfoTipos" and [Name] <> "CuentasContables - Asientos-MasInfoTiposMovimientos" and [Name] <> "CuentasContables - Documentos" and [Name] <> "CuentasContables - Documentos - Grupos" and [Name] <> "CuentasContables - Naturaleza" and [Name] <> "CuentasContables - Tipos" and [Name] <> "CuentasContables Grupos" and [Name] <> "CuentasContables-Clasificacion-Iva" and [Name] <> "CuentasContables-Clasificacion-Retefuente" and [Name] <> "CuentasContables_Asientos_Prefijos" and [Name] <> "CuentasContables_Asientos_Prefijos_Detalle" and [Name] <> "CuentasContables_Asientos_SenAIU" and [Name] <> "CuentasContables_Clasificacion" and [Name] <> "Cuentas_Contables_Bancos_Chequeras" and [Name] <> "CupoCreditoHistorico" and [Name] <> "DateSerial" and [Name] <> "Deducibles_Retefuente_Indep" and [Name] <> "Deducibles_Retefuente_Indep_Terceros" and [Name] <> "Departamentos" and [Name] <> "DepartamentosDIAN_Colombia" and [Name] <> "Dependientes_Economincos_Familiares" and [Name] <> "DesctosCondicionados" and [Name] <> "DestinoCCA_Clasificaciones" and [Name] <> "DestinoCCA_Codeudores" and [Name] <> "DestinoCCA_Cuotas" and [Name] <> "DestinoCCA_M_Inventarios" and [Name] <> "DestinoCCD_Clasificaciones" and [Name] <> "DestinoCiudades" and [Name] <> "DestinoCuentasContables" and [Name] <> "DestinoCuentasContables - Asientos" and [Name] <> "DestinoCuentasContables - Asientos - Detalles" and [Name] <> "DestinoCuentasContables - Documentos" and [Name] <> "DestinoCuentasContables - Tipos" and [Name] <> "DestinoDepartamentos" and [Name] <> "DestinoDocAutomaticos" and [Name] <> "DestinoDocumentos Cruces" and [Name] <> "DestinoEmpresas" and [Name] <> "DestinoEventos-Programacion" and [Name] <> "DestinoEventosTipos" and [Name] <> "DestinoFormas De Pago" and [Name] <> "DestinoForma_De_Pago_Detallada" and [Name] <> "DestinoForma_De_Pago_Tarjetas" and [Name] <> "DestinoInventarios" and [Name] <> "DestinoInventarios - AgrupaciónDos" and [Name] <> "DestinoInventarios - AgrupaciónUno" and [Name] <> "DestinoInventarios - Bodegas" and [Name] <> "DestinoInventarios-Lotes" and [Name] <> "DestinoMoneda_Tipos" and [Name] <> "DestinoNomina_Cargos" and [Name] <> "DestinoNomina_Historica" and [Name] <> "DestinoNomina_SS_Novedades_Valores" and [Name] <> "DestinoN_A_ Detalles" and [Name] <> "DestinoPdetalles" and [Name] <> "DestinoSucursales" and [Name] <> "DestinoTerceros" and [Name] <> "DestinoTerceros - ClasificaciónDos" and [Name] <> "DestinoTerceros - ClasificaciónUno" and [Name] <> "DestinoTerceros - Contratos" and [Name] <> "DestinoTerceros - Direcciones" and [Name] <> "DestinoTerceros - Tipo de Identificación" and [Name] <> "DestinoTerceros - ZonaDos" and [Name] <> "DestinoTerceros - ZonaUno" and [Name] <> "DestinoUnidadesDeMedida" and [Name] <> "DestinoVehiculos" and [Name] <> "DestinoVehiculos_CargoReparacion" and [Name] <> "DestinoVehiculos_TipoReparacion" and [Name] <> "Detalles_Contable_SI" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso0" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso0_0" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso0_0_OtrosImpuestos" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso0_OtrosImpuestos" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso1" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso1_OtrosImpuestos" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso2_2" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-Paso2_2_OtrosImpuestos" and [Name] <> "Devolucion de Mercancias Proveedores -Contabilizacion-PasoRetFC" and [Name] <> "Devolucion de Mercancias Proveedores -SenalIvaCosto" and [Name] <> "Devoluciones_Por_Cliente" and [Name] <> "DiasAfiliacion" and [Name] <> "DiasAfiliacionOP" and [Name] <> "DiasAfiliacionVacac_2" and [Name] <> "DiasDeContratos" and [Name] <> "DiasDelMes" and [Name] <> "DiaSemana" and [Name] <> "DiasFonso" and [Name] <> "DiasNominaTercero" and [Name] <> "DiasNominaTercero_Concepto" and [Name] <> "DiasSumaFecha" and [Name] <> "Diferidos_Ingresos_Paso1" and [Name] <> "Diferidos_Ingresos_Paso2" and [Name] <> "Diferidos_Ingresos_Paso3" and [Name] <> "Diferidos_Paso1" and [Name] <> "Diferidos_Paso2" and [Name] <> "Diferidos_Paso3" and [Name] <> "DigitoVerificador" and [Name] <> "Dir_Tercero_Principal" and [Name] <> "Dir_tercero_sucursal" and [Name] <> "DisenioIventariosCamposFormulas" and [Name] <> "Disenio_Inventario_Detalle_OP" and [Name] <> "Distritos" and [Name] <> "DocAutomaticos" and [Name] <> "DocSecSaludSinFV" and [Name] <> "DocsNIIF" and [Name] <> "Documentos Cruces" and [Name] <> "Documentos_Configuracion_Actualizar_Precios" and [Name] <> "Documentos_Cruces_Informes" and [Name] <> "Documentos_Cruces_Informes_OS" and [Name] <> "Documentos_Disenio_FV_Agrupada_CCostos" and [Name] <> "Documentos_Disenio_FV_Agrupada_Grupo_Dos" and [Name] <> "Documentos_Disenio_FV_Agrupada_Producto" and [Name] <> "Documentos_Disenio_FV_Agrupada_Producto_SinLote" and [Name] <> "Documentos_Grupos" and [Name] <> "Documentos_Tipo_TRM" and [Name] <> "Dotaciones_Cargos" and [Name] <> "Dotaciones_Terceros" and [Name] <> "dtproperties" and [Name] <> "EcuadorCalculoRetencion" and [Name] <> "Ecuador_BusqRet_compras" and [Name] <> "Ecuador_BusqRet_compras_CONTADOR" and [Name] <> "Ecuador_BusqRet_Facturas_sin_comprobantes" and [Name] <> "Ecuador_BusqRet_Facturas_sin_comprobantes_Contador" and [Name] <> "Ecuador_BusqVentas" and [Name] <> "Ecuador_BusqVentas_Contador" and [Name] <> "Ecuador_Canton" and [Name] <> "Ecuador_ClaveAcceso_Fact_Electronica" and [Name] <> "Ecuador_Cobro_Juridico" and [Name] <> "Ecuador_CodigoRegimen" and [Name] <> "Ecuador_CodProveedor_FE" and [Name] <> "Ecuador_CompRetBusqueda" and [Name] <> "Ecuador_ComprobanteRetencion" and [Name] <> "Ecuador_Dir_Formularios_SRI" and [Name] <> "Ecuador_DistritoAduanero" and [Name] <> "Ecuador_Exportacion" and [Name] <> "Ecuador_Fact_Electronica_XML" and [Name] <> "Ecuador_FormasDePago" and [Name] <> "Ecuador_FormularioComprobanteRetencionSRI_1" and [Name] <> "Ecuador_FormularioConceptosDeduccion_SRI" and [Name] <> "Ecuador_Formulario_104" and [Name] <> "Ecuador_GenArchivoFormasPago" and [Name] <> "Ecuador_GenArchivoPlanoAuxAts" and [Name] <> "Ecuador_GenArchivoPlanoContador_0_Reforma" and [Name] <> "Ecuador_GenArchivoPlanoContador_2" and [Name] <> "Ecuador_GenArchivoPlanoContador_3" and [Name] <> "Ecuador_GenArchivoPlanoContador_4" and [Name] <> "Ecuador_GenArchivoPlanoContador_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_0_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_1_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_2" and [Name] <> "Ecuador_GenArchivoPlano_3" and [Name] <> "Ecuador_GenArchivoPlano_4" and [Name] <> "Ecuador_GenArchivoPlano_ATS_Anulados" and [Name] <> "Ecuador_GenArchivoPlano_ATS_CompensacionVentas" and [Name] <> "Ecuador_GenArchivoPlano_Ats_ComprasContador_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_ATS_ComprasRembolsoContador_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_ATS_ComprasRembolso_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_ATS_Compras_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_ATS_Exportacion" and [Name] <> "Ecuador_GenArchivoPlano_ATS_Ventas" and [Name] <> "Ecuador_GenArchivoPlano_ATS_VentasContador" and [Name] <> "Ecuador_GenArchivoPlano_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_REOC_2_Contador_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_REOC_2_Reforma" and [Name] <> "Ecuador_GenArchivoPlano_Ventas" and [Name] <> "Ecuador_GenArchivoPlano_VentasContador_1A" and [Name] <> "Ecuador_GenArchivoPlano_VentasContador_1B" and [Name] <> "Ecuador_GenArchivoPlano_VentasContador_Descuentos" and [Name] <> "Ecuador_GenArchivoPlano_Ventas_0" and [Name] <> "Ecuador_GenArchivoPlano_Ventas_1" and [Name] <> "Ecuador_GenArchivoPlano_Ventas_NC" and [Name] <> "Ecuador_Genarchivo_Informante" and [Name] <> "Ecuador_Genarchivo_Informante_Contador" and [Name] <> "Ecuador_GenArchivo_VentasEstablecimiento" and [Name] <> "Ecuador_GenArchivo_VentasEstablecimiento_Contador" and [Name] <> "Ecuador_GenArchivo_VentasFormasDePago" and [Name] <> "Ecuador_MovFormasdePago" and [Name] <> "Ecuador_Nomina_Retefuente_TotalDeduciblePersonal" and [Name] <> "Ecuador_Origen_Ingresos" and [Name] <> "Ecuador_PaisPago" and [Name] <> "Ecuador_ParaisosFiscales" and [Name] <> "Ecuador_Parroquias" and [Name] <> "Ecuador_ProveedorResolucionFacturacion" and [Name] <> "Ecuador_ResolucionFactura_FC" and [Name] <> "Ecuador_SUBCompras" and [Name] <> "Ecuador_SUBSucursales" and [Name] <> "Ecuador_SUBVentas_ATS" and [Name] <> "Ecuador_Sustentos_Reembolsos" and [Name] <> "Ecuador_SustentoTributario" and [Name] <> "Ecuador_TieneCtaRetencion" and [Name] <> "Ecuador_TipoComprobante" and [Name] <> "Ecuador_TipoPago" and [Name] <> "Ecuador_TipoProveedores" and [Name] <> "Empresas" and [Name] <> "Empresas_Backup" and [Name] <> "Empresas_Direcciones" and [Name] <> "Empresa_PuntoEmision" and [Name] <> "Empresa_ResolucionFacturacion" and [Name] <> "Entrada_Producto_Terminado_GenerarSA_Optim" and [Name] <> "EPTxOrdenProduccion" and [Name] <> "EsAnticipoImportacion" and [Name] <> "EstadodeResultadoComparativo_Paso1" and [Name] <> "EstadodeResultadoComparativo_Paso1_Encabezados" and [Name] <> "EstadoResCentroCostosHorizontal_Paso1" and [Name] <> "Estado_Cuenta_Circulares" and [Name] <> "Estado_Cuenta_Circular_Paso1" and [Name] <> "Estado_Cuenta_Circular_Paso_0" and [Name] <> "Estado_Cuenta_GeneraCE" and [Name] <> "Estado_Cuenta_Morosa" and [Name] <> "Estado_Cuenta_Paso0" and [Name] <> "Estado_Cuenta_Paso0_Ext" and [Name] <> "Estado_Cuenta_Proyec_PagosAuto" and [Name] <> "Estado_Cuenta_ProyVenc_5c_Paso0" and [Name] <> "Estado_Cuenta_ProyVenc_Paso0" and [Name] <> "Estado_de_Cuenta_30_60_90_Paso1" and [Name] <> "Estado_de_Cuenta_Factura_Abono_Saldo_Paso_1" and [Name] <> "Estado_Resultados_Centro_Costos_Paso_1" and [Name] <> "Eventos-ConvPizza" and [Name] <> "Eventos-Programacion" and [Name] <> "Eventos-Restricciones" and [Name] <> "Eventos-Salones" and [Name] <> "EventosInvNinosAdultos" and [Name] <> "EventosTipos" and [Name] <> "ExistenciasLotes" and [Name] <> "Existencias_Empresa" and [Name] <> "Existencias_Fecha" and [Name] <> "Existencias_Fecha_Rotacion" and [Name] <> "Existencias_Fecha_Talla_Color" and [Name] <> "Exportacion_Empleados" and [Name] <> "Factura de Venta Cruces" and [Name] <> "Factura de Venta Cruces Pedidos" and [Name] <> "Factura de venta Cruces Remisiones" and [Name] <> "Facturacion_Bloque" and [Name] <> "Facturacion_Bloque_Ingresos_Terceros" and [Name] <> "Facturacion_Bloque_Reemplazar_Cuentas" and [Name] <> "Factura_de_Compra_Contabilizacion_BaseAcum" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso0" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso0_0" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso0_0_OtrosImpuestos" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso0_OtrosImpuestos" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso1" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso1_OtrosImpuestos" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso2" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso2_OtrosImpuestos" and [Name] <> "Factura_de_Compra_Contabilizacion_Paso_Aporte" and [Name] <> "Factura_de_Compra_Contabilizacion_RetAcum" and [Name] <> "Factura_de_Compra_Contabilizacion_SenalIvaCosto" and [Name] <> "Factura_de_Compra_Cruces_Paso1" and [Name] <> "Factura_de_Compra_GastoAlCosto_Paso1" and [Name] <> "Factura_de_Compra_ReteIndepen_Auditoria" and [Name] <> "Factura_de_Compra_ReteIndepen_Paso0" and [Name] <> "Factura_de_Compra_ReteIndepen_Paso1" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_Deducciones" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_Deducciones2" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_Deducciones_SUB" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_Exentas" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_PagoDelMes" and [Name] <> "Factura_de_Compra_ReteIndepen_REFORMA_PagoDelMes_SUB" and [Name] <> "Factura_de_Compra_ReteIndepen_UltimPorc_REFORMA" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0_0" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0_0_Ingreso_Tercero" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0_0_OtrosImpuestos" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0_Ingreso_Terceros" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso0_OtrosImpuestos" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso1" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso1_Ingreso_Terceros" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso1_OtrosImpuestos" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso2" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso2_Ingreso_Tercero" and [Name] <> "Factura_de_Venta_Contabilizacion_Paso2_OtrosImpuestos" and [Name] <> "FC_maxRenglonRete" and [Name] <> "FC_maxRenglonReteALL" and [Name] <> "FeCamposPersonalizados" and [Name] <> "FechaCuota" and [Name] <> "FechaFinAfiliacionVacac_2" and [Name] <> "FechaInicioAfiliacion" and [Name] <> "FechaInicioAfiliacionOP" and [Name] <> "FechaInicioAfiliacionVacac_2" and [Name] <> "FechasHabiles" and [Name] <> "FechaSumaDias" and [Name] <> "FechaSumaDiasVac" and [Name] <> "FeDocumentosSoportePresentados" and [Name] <> "FeEstadoDocumentosPresentadosPeru" and [Name] <> "FeFacturasPresentadas" and [Name] <> "FeLicenciasEmpresas" and [Name] <> "FeLicenciasEmpresasPlanes" and [Name] <> "FeLicenciasEmpresasResoluciones" and [Name] <> "FeNominasPresentadas" and [Name] <> "FeNominasPresentadas_Relacion" and [Name] <> "FePlanesFacturacion" and [Name] <> "FeTagsCamposPersonalizados" and [Name] <> "FeTercerosActualizacion" and [Name] <> "FeTipoOperacion" and [Name] <> "Fe_CodigosInternacionales_Inventarios" and [Name] <> "FE_Documentos_Peso" and [Name] <> "FE_Empresas_ListaValores" and [Name] <> "FE_Empresas_TipoResponsabilidades" and [Name] <> "FE_Empresas_TiposEstablecimientos" and [Name] <> "FE_Empresas_TiposRepresentacion" and [Name] <> "FE_Empresas_TipoUsuarioAduanero" and [Name] <> "FE_Envios_Contingencia_Documentos" and [Name] <> "FE_EquivalenciasInventario" and [Name] <> "FE_FacturasNoWO" and [Name] <> "Fe_FormasDePago" and [Name] <> "FE_Ingresos_Terceros" and [Name] <> "Fe_Log" and [Name] <> "Fe_MedioPagos" and [Name] <> "Fe_Monedas" and [Name] <> "FE_Motivos_Notas" and [Name] <> "Fe_Paises" and [Name] <> "Fe_Periodos_Contingencia" and [Name] <> "Fe_Personalizados_Vehiculos_Peru" and [Name] <> "FE_Rips_CUPS" and [Name] <> "FE_Rips_Inventarios" and [Name] <> "Fe_Rips_MinSalud_Usuarios" and [Name] <> "FE_Rips_TipoServicio" and [Name] <> "FE_Salud_Cobertura" and [Name] <> "FE_Salud_InfoDocumento" and [Name] <> "FE_Salud_ModalidadContrato" and [Name] <> "FE_Salud_TerceroModalidadContrato" and [Name] <> "FE_Salud_TipoInfo" and [Name] <> "Fe_Salud_TipoOperacion" and [Name] <> "Fe_Salud_TipoPago" and [Name] <> "FE_Salud_TipoUsuario" and [Name] <> "FE_Sector_Salud_FormaPago" and [Name] <> "FE_Terceros_TipoResponsabilidades" and [Name] <> "Fe_TipoIdentificacion" and [Name] <> "FE_Total_Impuestos" and [Name] <> "FE_Total_Impuestos_2" and [Name] <> "Fe_Transporte" and [Name] <> "Fe_UnidadMedida" and [Name] <> "Filtro_liquidaciones_Liquidada_No_cancelada" and [Name] <> "Filtro_liquidaciones_Liquidada_y_Cancelada" and [Name] <> "Filtro_liquidaciones_No_Liquidadas" and [Name] <> "FNC_Auxiliar_Impuestos_Retenciones" and [Name] <> "FNC_Balance General Centro de Costos" and [Name] <> "FNC_Balance General Comparativo Aud" and [Name] <> "FNC_Balance General Comparativo_Auditoria" and [Name] <> "FNC_BalanceGenCentroCostosHorizontal_Paso1" and [Name] <> "FNC_Caja_Menor" and [Name] <> "FNC_CalcularIVA" and [Name] <> "FNC_CasteoDinamico" and [Name] <> "FNC_Certificado Retefuente" and [Name] <> "FNC_Certificado ReteIca" and [Name] <> "FNC_Certificado ReteIva" and [Name] <> "FNC_Certificado_Rete_CREE" and [Name] <> "FNC_Cheques_Posfechados_Girados" and [Name] <> "FNC_Comision_Recaudo_Descto" and [Name] <> "FNC_Comision_Recaudo_Paso0" and [Name] <> "FNC_Comision_Recaudo_Paso1" and [Name] <> "FNC_Comision_Recaudo_Paso2" and [Name] <> "FNC_COMPARA_VALORES" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso0" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso0_OtrosImpuestos" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso1" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso1_OtrosImpuestos" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso2" and [Name] <> "FNC_Compra_Remision-Contabilizacion-Paso2_OtrosImpuestos" and [Name] <> "FNC_Compra_Remision-Contabilizacion_SenalIvaCosto" and [Name] <> "FNC_Comprobante de Diario" and [Name] <> "FNC_ConciliacionBancaria" and [Name] <> "FNC_ConciliacionBancariaAuto_ExtractoAdmin_SQL" and [Name] <> "FNC_Consignacion Bancaria-Contabilizacion-CtaCaja" and [Name] <> "FNC_Consignacion Bancaria-Contabilizacion-Paso0" and [Name] <> "FNC_Consignacion Bancaria-Contabilizacion-Paso1" and [Name] <> "FNC_Consignacion Bancaria-Contabilizacion-Paso2" and [Name] <> "FNC_Cuenta de Cobro-Contabilizacion-Paso1" and [Name] <> "FNC_Cuenta de Cobro-Contabilizacion-Paso2" and [Name] <> "FNC_Descuadres" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso0" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso0_0" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso0_0_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso0_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso1" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso1_Mul" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso1_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso2" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso2_Mul" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-Paso2_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Mercancias Clientes -Contabilizacion-PasoRetFV" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso0" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso0_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso1" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso1_OtrosImpuestos" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso2" and [Name] <> "FNC_Devolucion de Remision-Contabilizacion-Paso2_OtrosImpuestos" and [Name] <> "FNC_Devolucion_Mercancia_Clientes_Paso0_1" and [Name] <> "FNC_Devolucion_Mercancia_Clientes_Paso0_1_OtrosImpuestos" and [Name] <> "FNC_Documentos Sin Contabilizar" and [Name] <> "FNC_Entrada a Almacen-Contabilizacion-Paso0" and [Name] <> "FNC_Entrada a Almacen-Contabilizacion-Paso1" and [Name] <> "FNC_Entrada a Almacen-Contabilizacion-Paso2" and [Name] <> "FNC_EntradaProdTerminado-Contabilizacion-Paso0" and [Name] <> "FNC_EntradaProdTerminado-Contabilizacion-Paso1" and [Name] <> "FNC_EntradaProdTerminado-Contabilizacion-Paso2" and [Name] <> "FNC_EstadoCarteraVencimientoMesAMes" and [Name] <> "FNC_EstadodeResultadoComparativo_Aud" and [Name] <> "FNC_EstadodeResultadosComparativoAuditoria" and [Name] <> "FNC_Estados_Finanacieros_Analisis_Bce" and [Name] <> "FNC_Estados_Financieros_CambioSitFinan" and [Name] <> "FNC_Estado_Cuenta_FV_SI_SinPago" and [Name] <> "FNC_Estado_Cuenta_Recaudos" and [Name] <> "FNC_Factura Extranjera -Contabilizacion-Paso0" and [Name] <> "FNC_Factura Extranjera -Contabilizacion-Paso1" and [Name] <> "FNC_Factura Extranjera -Contabilizacion-Paso2" and [Name] <> "FNC_FACTURA_DE_VENTA_PASO0_1" and [Name] <> "FNC_FACTURA_DE_VENTA_PASO0_1_Ingreso_Terceros" and [Name] <> "FNC_FACTURA_DE_VENTA_PASO0_1_OtrosImpuestos" and [Name] <> "FNC_InfLibro Auxiliar Ccostos Agrupado" and [Name] <> "FNC_Inventarios-Auditoria-CantNeg" and [Name] <> "FNC_Inventarios-Auditoria-CostoPromNegativo" and [Name] <> "FNC_Inventarios-Auditoria-DMP" and [Name] <> "FNC_INVENTARIO_COSTO_PROMEDIO" and [Name] <> "FNC_INVENTARIO_COSTO_PROMEDIO_NIIF" and [Name] <> "FNC_Libro Auxiliar C Costos Agrupado" and [Name] <> "FNC_Libro Auxiliar C Costos Mes" and [Name] <> "FNC_Libro Auxiliar C Costos Mes Tercero" and [Name] <> "FNC_Libro Diario Oficial Paso1" and [Name] <> "FNC_Libro Diario Oficial Paso2_Dinamico" and [Name] <> "FNC_Libro Diario Por Doc" and [Name] <> "FNC_Libros Oficiales-Numeraciones" and [Name] <> "FNC_LibrosPeruDyC" and [Name] <> "FNC_Libro_Cuenta_Razon" and [Name] <> "FNC_Medios_Distritales_01Retfte" and [Name] <> "FNC_Medios_Distritales_03Compras" and [Name] <> "FNC_Medios_Distritales_03Compras_CXP" and [Name] <> "FNC_Medios_Distritales_04Ingresos" and [Name] <> "FNC_Medios_Mageneticos_04_RetfteQueLePract" and [Name] <> "FNC_Medios_Magneticos_07IvaDescontable" and [Name] <> "FNC_Medios_Magneticos_ImpoConsumoGasto" and [Name] <> "FNC_Medios_Magneticos_IVAGasto" and [Name] <> "FNC_Medios_Magneticos_ValidacionFondo" and [Name] <> "FNC_Medios_Magneticos_ValidacionFondo_X_AsientoContable" and [Name] <> "FNC_RecuperarEstadoCuenta_CarteraDias_Paso1" and [Name] <> "FNC_Remision-Contabilizacion-Paso0" and [Name] <> "FNC_Remision-Contabilizacion-Paso0_OtrosImpuestos" and [Name] <> "FNC_Remision-Contabilizacion-Paso1" and [Name] <> "FNC_Remision-Contabilizacion-Paso1_OtrosImpuestos" and [Name] <> "FNC_Remision-Contabilizacion-Paso2" and [Name] <> "FNC_Remision-Contabilizacion-Paso2_OtrosImpuestos" and [Name] <> "FNC_Salida de Almacen-Contabilizacion-Paso0" and [Name] <> "FNC_Salida de Almacen-Contabilizacion-Paso1" and [Name] <> "FNC_Salida de Almacen-Contabilizacion-Paso2" and [Name] <> "FNC_ValidaTercero2FondoAporte" and [Name] <> "fnPasarMayusculasMinusculas" and [Name] <> "fn_AuditoriaIsCambio" and [Name] <> "fn_diagramobjects" and [Name] <> "Fondos" and [Name] <> "Fondos_Config_Peru" and [Name] <> "Fondo_Cesantias" and [Name] <> "Formas De Pago" and [Name] <> "FormatoEspacios" and [Name] <> "Formato_PLE_Compra" and [Name] <> "Forma_De_Pago_Bonos" and [Name] <> "Forma_De_Pago_Detallada" and [Name] <> "Forma_De_Pago_Grupos" and [Name] <> "Forma_De_Pago_Tarjetas" and [Name] <> "FuncionesDisponibles" and [Name] <> "Funcion_XLS_Nonima_TiempoLaboradoTercero" and [Name] <> "FUNC_Inventarios_CostoPromedio" and [Name] <> "FUNC_Inventarios_CuentaMesAnalisis" and [Name] <> "FUNC_Inventarios_ExistenciasTotales" and [Name] <> "FUNC_Inventarios_UltimaFechaCompra" and [Name] <> "FUNC_Inventarios_UltimaFechaVenta" and [Name] <> "FUNC_PresupCCostosBalancePaso1" and [Name] <> "FUNC_PresupCCostosBalancePaso2" and [Name] <> "FUNC_PresupCCostosPaso1" and [Name] <> "FUNC_PresupCCostosPaso2" and [Name] <> "FunReformaParafiscal" and [Name] <> "FunReformaParafiscal_OPTIM" and [Name] <> "FunReformaParafiscal_TIPO" and [Name] <> "FunReformaParafiscal_VAC" and [Name] <> "Fun_Abona_A_NotaContable_1" and [Name] <> "Fun_Abona_A_NotaContable_2" and [Name] <> "Fun_Comprueba_Fecha" and [Name] <> "FV_Canceladas_Ecuador" and [Name] <> "GenerarSAProdSimpl" and [Name] <> "GetAsientoSectorSalud" and [Name] <> "GetFeSectorSalud" and [Name] <> "getValueConstantes" and [Name] <> "Historico_Cartera_Cliente_FV" and [Name] <> "Historico_Cartera_Cliente_RC" and [Name] <> "IdAsientoNuevoDocAutomatico" and [Name] <> "IdCuentaAporteVacac" and [Name] <> "IdCuentaContable_ActivoFijo_Peru" and [Name] <> "IdCuentaNomina" and [Name] <> "IdCuentaNominaOP" and [Name] <> "IdCuentaNominaSolidaridad" and [Name] <> "Importacion_Aranceles" and [Name] <> "Importacion_Clasificacion" and [Name] <> "Importacion_Contabilizacion_Paso0" and [Name] <> "Importacion_Contabilizacion_Paso1" and [Name] <> "Importacion_Contabilizacion_Paso2" and [Name] <> "Importacion_DatosGenerales" and [Name] <> "Importacion_DatosGnales" and [Name] <> "Importacion_Liquidacion_Costos" and [Name] <> "Importacion_Liquidacion_CostosParcial_Paso1" and [Name] <> "Importacion_Liquidacion_Costos_Parcial2" and [Name] <> "Importacion_Liquidacion_Costos_Paso1" and [Name] <> "Importacion_Pasos_Auditoria" and [Name] <> "Importacion_Puertos" and [Name] <> "Importacion_tipos" and [Name] <> "Importación_pasos" and [Name] <> "Impto_Bancario_Monto" and [Name] <> "Impto_Bancario_Temp" and [Name] <> "Impuestos_DatosAdicionales" and [Name] <> "Impuestos_DatosAdicionales_Info" and [Name] <> "Impuestos_OtrosImpuestosAsumidos" and [Name] <> "Impuestos_OtrosImpuestosInventarios" and [Name] <> "Impuestos_OtrosImpuestosPorRenglon" and [Name] <> "Impuestos_OtrosTiposImpuestos" and [Name] <> "Impuestos_OtrosTiposImpuestos_Tarifas" and [Name] <> "Impuesto_Auxiliar_Iva_BaseRet" and [Name] <> "Indicadores Financieros" and [Name] <> "Indicadores Financieros - Empresas" and [Name] <> "Indicadores Financieros - Tipos" and [Name] <> "IndicadoresFinanGraficas" and [Name] <> "InfInventariosAXI_Paso0" and [Name] <> "InfInventariosAXI_Paso00" and [Name] <> "InfInventariosAXI_Paso1" and [Name] <> "InfInventariosAXI_Paso2" and [Name] <> "InfInventariosAXI_Paso3" and [Name] <> "InfLibro_Auxiliar" and [Name] <> "InfLibro_AuxiliarActivoFijo" and [Name] <> "InfLibro_AuxiliarCheque" and [Name] <> "InfLibro_AuxiliarDiferidos" and [Name] <> "InfLibro_AuxiliarNit" and [Name] <> "InfLibro_AuxiliarNormal" and [Name] <> "InfLibro_AuxiliarNormalPeru" and [Name] <> "InfLibro_AuxiliarNormalPeru_Ene" and [Name] <> "InfLibro_AuxiliarTercero" and [Name] <> "InfLibro_Auxiliar_Ccostos" and [Name] <> "InformeAlquilerPorHoras" and [Name] <> "Informe_Compras_Dian" and [Name] <> "Informe_Estado_Cuenta_Circulares" and [Name] <> "Informe_Estado_Cuenta_Edades_5c" and [Name] <> "Informe_Estado_Cuenta_Edades_5c_Ext" and [Name] <> "Informe_Estado_Cuenta_ProyVenc" and [Name] <> "Informe_Estado_Cuenta_ProyVenc_5c" and [Name] <> "Inf_Diario_Caja_FP" and [Name] <> "Inf_Diario_Caja_Resumido_FPago_Paso1" and [Name] <> "Inf_Diario_Caja_Resumido_Saldo_Inicial" and [Name] <> "Inf_Diario_Caja_Ret" and [Name] <> "Instrucciones_Automaticas" and [Name] <> "INTERSECTS" and [Name] <> "INTERSECTS2" and [Name] <> "InvClasifCostos" and [Name] <> "InventarioExist" and [Name] <> "Inventarios" and [Name] <> "Inventarios - AgrupaciónCinco" and [Name] <> "Inventarios - AgrupaciónCuatro" and [Name] <> "Inventarios - AgrupaciónDiez" and [Name] <> "Inventarios - AgrupaciónDos" and [Name] <> "Inventarios - AgrupaciónNueve" and [Name] <> "Inventarios - AgrupaciónOcho" and [Name] <> "Inventarios - AgrupaciónSeis" and [Name] <> "Inventarios - AgrupaciónSiete" and [Name] <> "Inventarios - AgrupaciónTres" and [Name] <> "Inventarios - AgrupaciónUno" and [Name] <> "Inventarios - Bodegas" and [Name] <> "Inventarios - Por Bodega" and [Name] <> "Inventarios - Propiedades" and [Name] <> "Inventarios - Terceros" and [Name] <> "Inventarios Impresion" and [Name] <> "Inventarios-CodBarras-Atributos" and [Name] <> "Inventarios-CodBarras-Controles" and [Name] <> "Inventarios-CodBarras-Imprimible" and [Name] <> "Inventarios-CodBarras-IndicePlantilla" and [Name] <> "Inventarios-CodBarras-Plantillas" and [Name] <> "Inventarios-CodBarras-Seleccionados" and [Name] <> "Inventarios-Lotes" and [Name] <> "InventariosSeriales" and [Name] <> "Inventarios_AgrupacionDinamica" and [Name] <> "Inventarios_Caracteristicas" and [Name] <> "Inventarios_Caracteristicas_Detalle" and [Name] <> "Inventarios_Clases" and [Name] <> "Inventarios_Cod_Barras_Campos" and [Name] <> "Inventarios_Cod_Barras_Config" and [Name] <> "Inventarios_Cod_Barras_Config_Encab" and [Name] <> "Inventarios_Cod_Barras_Config_Grupo" and [Name] <> "Inventarios_Cod_Barras_Equivalencia" and [Name] <> "Inventarios_Colores" and [Name] <> "Inventarios_Colores_Detalle" and [Name] <> "Inventarios_Conversion" and [Name] <> "Inventarios_Descuento_Tercero" and [Name] <> "Inventarios_excepciones" and [Name] <> "Inventarios_Excepciones_Categorias" and [Name] <> "Inventarios_Excepciones_fechas" and [Name] <> "Inventarios_Excepciones_fechasConfiguracion" and [Name] <> "Inventarios_Excepciones_Generos" and [Name] <> "Inventarios_Excepciones_GenerosPorProducto" and [Name] <> "Inventarios_Impresion_Configuracion" and [Name] <> "Inventarios_Lista_Precios_Otra_Moneda" and [Name] <> "Inventarios_LstPrecios_Por_Cantidad" and [Name] <> "Inventarios_LstPrecios_Por_Cantidad_Config_Masivo" and [Name] <> "Inventarios_Notas" and [Name] <> "Inventarios_Perdidas" and [Name] <> "Inventarios_Registrados" and [Name] <> "Inventarios_Seriales" and [Name] <> "Inventarios_SerialesCargue" and [Name] <> "Inventarios_SerialesTmpMigracion" and [Name] <> "Inventarios_SerialesTmpModificacionBodegasMigra" and [Name] <> "Inventarios_Tallas" and [Name] <> "Inventarios_Tallas_Detalles" and [Name] <> "Inventarios_Tipos" and [Name] <> "InvFichaTec" and [Name] <> "InvFichaTec_RutaProduccion" and [Name] <> "iter$charlist_to_tbl" and [Name] <> "iter$charlist_to_tbl_ntext" and [Name] <> "iter$simple_intlist_to_tbl" and [Name] <> "iter$simple_intlist_to_tbl_CC" and [Name] <> "iter$simple_intlist_to_tbl_Cuentas" and [Name] <> "Iva" and [Name] <> "Iva-Impuestos" and [Name] <> "Iva-Renglon-Cuentas" and [Name] <> "IvaPaisDefault" and [Name] <> "Iva_Caracteristica" and [Name] <> "Iva_Fijos" and [Name] <> "Libros oficiales-Numeracion Libros" and [Name] <> "Libros_Peru_TipoRenta" and [Name] <> "LicenciasValidas" and [Name] <> "Liq_Vacaciones_Libro" and [Name] <> "Lista_Precio_Tercero" and [Name] <> "LogActualizacion" and [Name] <> "ManejImpuestos" and [Name] <> "ManejImpuestos_2" and [Name] <> "Mantenimientos" and [Name] <> "MEDIOSMAGNETICOS_ANEXO1001" and [Name] <> "MEDIOS_CESANTIAS_PAGO_EMPLEADO" and [Name] <> "Medios_Distritales_02Iva" and [Name] <> "Medios_Distritales_02RetfteQueLePract" and [Name] <> "Medios_Distritales_02_AbonaA" and [Name] <> "Medios_Magneticos_2276" and [Name] <> "Medios_Magneticos_2_Paso" and [Name] <> "Medios_Magneticos_2_paso_0_1" and [Name] <> "Medios_Magneticos_Auditoria_Retencion_ReteIva" and [Name] <> "Medios_Magneticos_Auditoria_Retencion_ReteIva2" and [Name] <> "Medios_Magneticos_Detalles" and [Name] <> "Medios_Magneticos_Detalles_Anexos" and [Name] <> "Medios_Magneticos_Detalles_Aportes" and [Name] <> "Medios_Magneticos_Detalles_Cuentas" and [Name] <> "Medios_Magneticos_Log" and [Name] <> "Medios_Magneticos_Nomina_Certificado_Ingreso_Retencion_DiasProm" and [Name] <> "Medios_Magneticos_Nomina_Certificado_Ingreso_Retencion_TotalPromedio" and [Name] <> "Medios_Magneticos_RetAsumida" and [Name] <> "Medios_Magneticos_Tipos" and [Name] <> "Medios_Magneticos_Tipos_Codigos" and [Name] <> "Medios_Magneticos_Tipos_Contratos" and [Name] <> "Memorandos_Terceros" and [Name] <> "Memorandos_Tipos" and [Name] <> "MenuEmergente" and [Name] <> "MenuEmergente2" and [Name] <> "MetodoPago_DIAN" and [Name] <> "MigracionNew_CamposPlantilla" and [Name] <> "MigracionNew_InformacionMigrar" and [Name] <> "MigracionNew_NombrePlantillas" and [Name] <> "MigracionNew_ValidacionTablas" and [Name] <> "Migracion_AsignaCamposTmp" and [Name] <> "Migracion_Log" and [Name] <> "Migracion_TablasCamposRelacion" and [Name] <> "Modalidad_Contratos" and [Name] <> "ModicaElementoArray" and [Name] <> "Moneda_Extranjera_Caja_Paso0" and [Name] <> "Moneda_Extranjera_Caja_Paso1" and [Name] <> "Moneda_Extranjera_Cruces" and [Name] <> "Moneda_Extranjera_Paso0" and [Name] <> "Moneda_Extranjera_Paso1" and [Name] <> "Moneda_Extranjera_Paso1_NIIF" and [Name] <> "Moneda_Tipos" and [Name] <> "Moneda_TRM" and [Name] <> "Motivos_Contingencia" and [Name] <> "Motivos_Devolucion_Notas" and [Name] <> "NIIF_ActivosFijos_Clasificacion" and [Name] <> "NIIF_ActivosFijos_Deterioro_Anos" and [Name] <> "NIIF_AjusteVNR_Historial_InvDoc" and [Name] <> "NIIF_Base_Deterioro_CxC" and [Name] <> "NIIF_DeteriorCXC_Intervalos" and [Name] <> "NIIF_FormatosInforme" and [Name] <> "NIIF_InformeMultiColumna" and [Name] <> "NIIF_InformeMultiColumna_Paso0" and [Name] <> "NIIF_InformeMultiColumna_Paso1" and [Name] <> "NIIF_Informes" and [Name] <> "NIIF_Informes_Conceptos" and [Name] <> "NIIF_Informes_Configuracion" and [Name] <> "NIIF_Informes_Configuracion_Detalle" and [Name] <> "NIIF_Informes_Paso1" and [Name] <> "NIIF_Informes_Paso2" and [Name] <> "NIIF_Informes_Tipos" and [Name] <> "NIIF_Inventarios_VNR" and [Name] <> "NIIF_NVR_PromedioListaInventario" and [Name] <> "NIIF_Reclasificacion_Cuentas" and [Name] <> "NIIF_ResultadoDelEjercicio" and [Name] <> "NIIF_Revelaciones" and [Name] <> "NIIF_TasaInteres_Mercado" and [Name] <> "NIIF_ValidaConfigVNR" and [Name] <> "NIIF_VentasCompras_FinanCreaContab_Paso0" and [Name] <> "NIIF_VentasCompras_FinanCreaContab_Paso1" and [Name] <> "NIIF_VentasCompras_FinanProceso_Local" and [Name] <> "NIIF_VentasCompras_FinanProceso_NIIF" and [Name] <> "NIIF_VentasCompras_FinanProceso_Paso0" and [Name] <> "NIIF_VNR_PromedioListaPrecios" and [Name] <> "NIIF_VNR_PromedioVentas" and [Name] <> "NMes_ContratoIniAño" and [Name] <> "NomAbonaDetalladoAbona" and [Name] <> "Nombre_Cuenta_Niveles" and [Name] <> "NomCuentas_Estado_Resultados" and [Name] <> "Nomina_Aportes_TrabajadoTiemoParcial_Dias" and [Name] <> "Nomina_Area" and [Name] <> "Nomina_AuxiliarTransporte" and [Name] <> "Nomina_Auxilio_Transporte_Auditoria_Encab" and [Name] <> "Nomina_Años_Reduccion_Parafiscales" and [Name] <> "Nomina_Beneficios_Contrato" and [Name] <> "Nomina_Bonificacion" and [Name] <> "Nomina_Calculo_AuxiliarTransporte" and [Name] <> "Nomina_Cargos" and [Name] <> "Nomina_Certificado_Ingreso_Consecutivos" and [Name] <> "Nomina_Certificado_Ingreso_Retencion_0" and [Name] <> "N_Acumulados" and [Name] <> "N_A_ Detalles" and [Name] <> "N_A_Informes" and [Name] <> "N_A_Transporte" and [Name] <> "N_A_Transporte_Base" and [Name] <> "N_A_Transporte_Vr" and [Name] <> "N_Beneficios" and [Name] <> "N_Conceptos" and [Name] <> "N_Conceptos_Terceros" and [Name] <> "N_Contrato" and [Name] <> "N_Contrato_Prorroga" and [Name] <> "N_C_Agrupacion" and [Name] <> "N_C_Agrupamiento" and [Name] <> "N_Detalles" and [Name] <> "N_Festivos" and [Name] <> "N_Novedades" and [Name] <> "N_Pagos_Prestamos_Entidad" and [Name] <> "N_Planilla" and [Name] <> "N_Predeterminados" and [Name] <> "N_SubDetalles" and [Name] <> "N_SueldosHistorico" and [Name] <> "N_Terceros" and [Name] <> "N_Tipos" and [Name] <> "N_TiposContrato" and [Name] <> "N_T_SubDetalles" and [Name] <> "__RefactorLog")),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [Name] = "Terceros"),
				    dbo_Terceros = #"Filas filtradas1"{[Schema="dbo",Item="Terceros"]}[Data],
				    #"Otras columnas quitadas" = Table.SelectColumns(dbo_Terceros,{"IdTipoIdentificacion", "Identificacion", "Nombre", "IdentificacionCiudad", "Propiedades", "Apellidos"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Otras columnas quitadas",{"IdTipoIdentificacion", "Identificacion", "Nombre", "Apellidos", "IdentificacionCiudad", "Propiedades"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas reordenadas", "Nombre_Terceros", each if [Apellidos]<>"" then [Nombre]&" "&[Apellidos] else [Nombre]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada",{"Apellidos"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

